aplicacion/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from aplicacion.views import *   

urlpatterns = [
    path('',index, name='index'),
    path('contacto/', contacto , name='contacto'),
    path('cursos/', cursos , name='cursos'),
    path('edicionproductos/', edicionproductos , name='edicionproductos'),
    path('editarusuario/', editarusuario , name='editarusuario'),
    path('faqs/', faqs , name='faqs'),
    path('formpago/', formpago , name='formpago'),
    path('horas/', horas , name='horas'),
    path('inicioSesionEstud/', inicioSesionEstud , name='inicioSesionEstud'),
    path('interfaz_de_compra/', interfaz_de_compra , name='interfaz_de_compra'),
    path('miscompras/', miscompras , name='miscompras'),
    path('perfil/', perfil , name='perfil'),
    path('perfilAdmin/', perfilAdmin , name='perfilAdmin'),
    path('profesores/', profesores , name='profesores'),
    path('ventas/', ventas , name='ventas'),
    path('form_registrarse/', form_registrarse , name='form_registrarse'),
    path('carrito/', carrito , name='carrito'),
    path('agregar_al_carrito/<int:producto_id>/', agregar_al_carrito, name='agregar_al_carrito'),
    path('quitar_del_carrito/<int:producto_id>/', quitar_del_carrito, name='quitar_del_carrito'),
    path('pagoexitoso/', pagoexitoso, name='pagoexitoso'),
    path('cerrarSesion/', cerrar_sesion, name='cerrarSesion'),
    

    #SECCION CRUD
    

    path('editar_producto_form/<int:id>/', editar_producto_form, name='editar_producto_form'),
    path('editar_perfil_form/<int:id>/', editar_perfil_form, name='editar_perfil_form'),
    path('editar_compra_form/<int:id>/', editar_compra_form, name='editar_compra_form'),
    path('confirmar_eliminacion_compra/<int:id>/', confirmar_eliminacion_compra, name='confirmar_eliminacion_compra'),
    path('confirmar_eliminacion_perfil/<int:id>/', confirmar_eliminacion_perfil, name='confirmar_eliminacion_perfil'),
    path('confirmar_eliminacion_producto/<int:id>/', confirmar_eliminacion_producto, name='confirmar_eliminacion_producto'),

    path('crear_producto/', crear_producto, name='crear_producto'),
    path('listar_productos/<int:id>', listar_productos, name='listar_productos'),
    path('editar_producto/<int:id>/', editar_producto, name='editar_producto'),
    path('eliminar_producto/<int:id>/', eliminar_producto, name='eliminar_producto'),
    path('crear_perfil/', crear_perfil, name='crear_perfil'),
    path('editar_perfil/<int:id>/', editar_perfil, name='editar_perfil'),
    path('eliminar_perfil/<int:id>/', eliminar_perfil, name='eliminar_perfil'),
    path('crear_compra/', crear_compra, name='crear_compra'),
    path('editar_compra/<int:id>/', editar_compra, name='editar_compra'),
    path('eliminar_compra/<int:id>/', eliminar_compra, name='eliminar_compra'),
    

    

    



]

# if settings.DEBUG:
#     urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urls del sitio

sitio/urls.py
from django.contrib import admin
from django.urls import path ,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplicacion.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]


#urls del sitio

aplicacion/models.py
from django.db import models

from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User

# Create your models here.
Cursos = [
    ('Clase B', 'Clase B'),
    ('Clase A2', 'Clase A2'),
    ('Clase A3', 'Clase A3'),
]

class Perfil(models.Model): 
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre_estudiante = models.CharField(max_length=50, unique=True, verbose_name="Nombre de estudiante")
    rut = models.CharField(max_length=10, unique=True, verbose_name="RUT", blank=True, null=True)
    correo = models.EmailField(unique=True, verbose_name="Correo Electrónico")
    cursos = models.CharField(max_length=20, choices=Cursos, verbose_name="Cursos")
    direccion = models.CharField(max_length=255, blank=True, null=True, verbose_name="Dirección")
    foto_perfil = models.ImageField(upload_to='usuarios/', blank=True, null=True, verbose_name="Foto de perfil")
    rol = models.CharField(max_length=20, choices=[('Administrador', 'Administrador'), ('Estudiante', 'Estudiante')], verbose_name="Rol")
    

    def __str__(self):
        return f"{self.nombre_estudiante} - {self.correo}"

class Producto(models.Model):
    nombre = models.CharField(max_length=100, verbose_name="Nombre del curso")
    precio = models.PositiveIntegerField( verbose_name="Precio")
    cursos = models.CharField(max_length=20, choices=Cursos, verbose_name="Cursos")
    cupos = models.PositiveIntegerField(verbose_name="Cupos", default=30)
    descripcion = models.TextField(verbose_name="Descripción del curso")
    imagen_curso = models.ImageField(upload_to='cursos/', verbose_name="Imagen Curso")


    def __str__(self):
        return self.nombre

class Compra(models.Model):
    nombre_curso = models.CharField(max_length=100, verbose_name="Nombre del curso")
    fecha_pedido = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de compra")
    precio = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Precio")
    estado = models.CharField(max_length=50, choices=[('Proceso', 'Proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], verbose_name="Estado")
    perfil = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Perfil", null=True, blank=True)

    def __str__(self):
        return f"Compra #{self.id} - {self.perfil.nombre_curso} - {self.precio}"
    
class DetalleCompra(models.Model):
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE, related_name='detalles')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name='detalles')
    def __str__(self):
        return f"{self.producto.nombre} x {self.tipo_pago}"
    



class CarritoItem(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE, null=True, blank=True)
    cantidad = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.producto.nombre}'


    @property
    def total_price(self):
        return self.cantidad * self.producto.precio

aplicacion/views.py
from django.contrib import messages  
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from aplicacion.forms import CompraForm, ComprarCursoForm, EditarPerfilForm, PagoForm, PerfilForm, ProductoForm, RegistroAdminForm,RegistroForm,form_login
from aplicacion.forms import ComprarCursoForm, EditarPerfilForm, PagoForm,RegistroForm,form_login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from aplicacion.models import CarritoItem, Compra, DetalleCompra, Perfil, Producto


def es_superuser(user):
    return user.is_superuser

def base(request):
    return render(request, 'Autoescuela/base.html')

def index(request):
    return render(request, 'Autoescuela/index.html')

def contacto(request):
    return render(request, 'Autoescuela/contacto.html')

def cursos(request):
    cursos = Producto.objects.all()
    comprar_curso_form = ComprarCursoForm()
    return render(request, 'Autoescuela/cursos.html', {'cursos': cursos, 'comprar_curso_form': comprar_curso_form})

def edicionproductos(request):
    return render(request, 'Autoescuela/edicionproductos.html')

def editarusuario(request):
    return render(request, 'Autoescuela/editarusuario.html')

def faqs(request):
    return render(request, 'Autoescuela/faqs.html')

def formpago(request):
    items_carrito = CarritoItem.objects.all()
    total = sum(item.producto.precio for item in items_carrito)  # Calcula el total del carrito

    if request.method == 'POST':
        form = PagoForm(request.POST)
        if form.is_valid():
            if request.user.is_authenticated:
                perfil = request.user
            else:
                perfil = None

            # Verificar si el usuario ya compró alguno de los cursos en el carrito
            for item in items_carrito:
                if Compra.objects.filter(perfil=perfil, detalles__producto=item.producto).exists():
                    messages.error(request, f'Ya compraste el curso {item.producto.nombre}.')
                    return redirect('carrito')

            # Crea la instancia de Compra
            compra = Compra.objects.create(
                nombre_curso=form.cleaned_data['nombre'],  # Ajusta según tus necesidades
                precio=total,
                estado='Proceso',
                perfil=perfil
            )

            # Crea las instancias de DetalleCompra asociadas a la compra
            for item in items_carrito:
                compra.detalles.create(
                    producto=item.producto,
                )

            # Vacía el carrito después de realizar la compra
            items_carrito.delete()

            return redirect('index')
    else:
        form = PagoForm()

    return render(request, 'Autoescuela/formpago.html', {'form': form, 'total': total})

def horas(request):
    return render(request, 'Autoescuela/horas.html')

def inicioSesionEstud(request):
    return render(request, 'Autoescuela/inicioSesionEstud.html')

def interfaz_de_compra(request):
    return render(request, 'Autoescuela/interfaz_de_compra.html')

def miscompras(request):
    compras = Compra.objects.filter(perfil=request.user).order_by('fecha_pedido')
    compras_con_id_local = [(idx + 1, compra) for idx, compra in enumerate(compras)]
    return render(request, 'Autoescuela/miscompras.html', {'compras_con_id_local': compras_con_id_local})


def perfil(request):
    # Asegurándonos de que se obtiene el perfil correcto del usuario
    usuario = Perfil.objects.get(usuario=request.user)

    if request.method == 'POST':
        # Instanciar el formulario con los datos POST y archivos, además del perfil existente
        form = EditarPerfilForm(request.POST, request.FILES, instance=usuario)
        if form.is_valid():
            form.save()  # Guardamos los cambios en el perfil
            messages.success(request, 'Perfil actualizado exitosamente.')
            return redirect('perfil')
    else:
        # Instanciar el formulario con el perfil existente
        form = EditarPerfilForm(instance=usuario)

    return render(request, 'Autoescuela/perfil.html', {'usuario': usuario, 'form': form})


    if request.method == 'POST':
        form = EditarPerfilForm(request.POST, request.FILES, instance=usuario)
        if form.is_valid():
            form.save()  # Guardamos los cambios en el perfil
            messages.success(request, 'Perfil actualizado exitosamente.')
            return redirect('perfil')
    else:
        form = EditarPerfilForm(instance=usuario)

    return render(request, 'Autoescuela/perfil.html', {'usuario': usuario, 'form': form})


# def perfilAdmin(request):
#     return render(request, 'Autoescuela/perfilAdmin.html')

def profesores(request):
    return render(request, 'Autoescuela/profesores.html')

def confirmar_eliminacion(request):
    return render(request, 'Autoescuela/profesores.html')

def ventas(request):
    return render(request, 'Autoescuela/confirmar_eliminacion.html')

def form_registrarse(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            
            print(f"Username: {username}, Email: {email}, Password: {password}")
            
            user = form.save(commit=False)
            user.set_password(password)
            user.save()
            
            print(f"User saved: {user}")
            
            user = authenticate(request, username=username, password=password)
            print(f"Authenticated user: {user}")
            
            if user is not None:
                login(request, user)
                
                perfil = Perfil.objects.create(usuario=user, correo=email, rol='Estudiante', nombre_estudiante=username)
                perfil.save()
                
                messages.success(request, 'Registro exitoso.')
                return redirect('login')
            else:
                messages.error(request, 'Error al autenticar el usuario.')
                print("Authentication failed.")
        else:
            messages.error(request, 'Formulario no válido. Corrige los errores indicados.')
            print("Formulario no válido.")
    else:
        form = RegistroForm()
    
    return render(request, 'Autoescuela/form_registrarse.html', {'form': form})





@login_required
def carrito(request):
    items_carrito = CarritoItem.objects.filter(compra=None)
    total = sum(item.total_price for item in items_carrito)
    tiene_items = items_carrito.exists()  # Verifica si hay items en el carrito

    return render(request, 'Autoescuela/carrito.html', {
        'items_carrito': items_carrito,
        'total': total,
        'tiene_items': tiene_items,  # Pasa esta variable al contexto del template
    })


def form_inicio_sesion(request):
    if request.method == 'POST':
        form = form_login(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('index')
    else:
        form = form_login()
    return render(request, 'login.html', {'form': form})


@login_required
def eliminar_carrito(request, producto_id):
    curso = get_object_or_404(Producto, id=producto_id)  # Ajustar el modelo
    curso.delete()
    messages.success(request, 'Curso eliminado')  # Ajustar el mensaje
    return redirect('carrito')


@login_required
def agregar_al_carrito(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    
    # Verificar si el usuario ya compró este curso
    if Compra.objects.filter(perfil=request.user, detalles__producto=producto).exists():
        messages.error(request, 'Ya has comprado este curso.')
        return redirect('cursos')
    
    # Verificar si el curso ya está en el carrito
    if CarritoItem.objects.filter(producto=producto, compra=None).exists():
        messages.error(request, 'Este curso ya está en tu carrito.')
        return redirect('cursos')
    
    # Si no existe, agregar el curso al carrito
    carrito_item, created = CarritoItem.objects.get_or_create(
        producto=producto, compra=None, defaults={'cantidad': 1}
    )
    
    if not created:
        carrito_item.cantidad += 1
        carrito_item.save()

    messages.success(request, 'Curso agregado al carrito.')
    return redirect('carrito')





@login_required
def quitar_del_carrito(request, producto_id):
    item = get_object_or_404(CarritoItem, id=producto_id, compra=None)
    item.delete()
    return redirect('carrito')

@login_required
def proceder_a_compra(request):
    carrito_items = CarritoItem.objects.filter(compra=None, usuario=request.user)  # Añadido usuario
    if carrito_items.exists():
        compra = Compra.objects.create(perfil=request.user, precio=sum(item.producto.precio for item in carrito_items), estado='Pendiente')
        carrito_items.update(compra=compra)
        return redirect('formpago')
    return redirect('ver_carrito')

def pagoexitoso(request):
    return render(request, 'Autoescuela/pagoexitoso.html')

def listar_cursos(request):
    cursos = Producto.objects.all()
    return render(request, 'Autoescuela/cursos.html', {'cursos': cursos})



def navbar_context(request):
    usuario_autenticado = request.user.is_authenticated
    tiene_compras = False

    if usuario_autenticado:
        try:
            perfil =request.user
            items_carrito = CarritoItem.objects.filter(compra__perfil=perfil, compra=None)
            tiene_compras = items_carrito.exists()
        except Perfil.DoesNotExist:
            pass

    return {
        'usuario_autenticado': usuario_autenticado,
        'tiene_compras': tiene_compras,
    }

def cerrar_sesion(request):
    CarritoItem.objects.all().delete()

aplicacion/templates/Autoescuela/FAQS.html
{% extends "Autoescuela/base.html" %}
{% load static %}


{% block title %}faqs{% endblock %}

{% block contenido %}


<div
    class="masthead1"
    style="background-image: url(img/auto.png);">
  </div>


  <div class="container mb-5">
    
    <div class="accordion" id="accordionPanelsStayOpenExample">
      <div class="accordion" id="accordionPanelsStayOpenExample">
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
              ¿Cuáles son los requisitos para inscribirme en el curso de manejo?
            </button>
          </h2>
          <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show">
            <div class="accordion-body">
              Ser mayor de 18 años, o tener 17 años acompañado de un tutor.
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
              ¿Cuál es el costo del curso y qué incluye?
            </button>
          </h2>
          <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse">
            <div class="accordion-body">
              El valor del curso es de $180.000 + IVA
              Incluye: 
              <br>
              Comunicación Vial 
              <br>
              Elementos del Tránsito 
              <br>
              Terminología Vial
              <br>
              Instrucciones y Reglas del Tránsito
              <br>
              Virajes
              <br>
              Adelantamiento y Sobrepasar
              <br>
              Estacionamiento y Detención
              <br>
              Velocidad
              <br>
              Mecánica Básica
              <br>
              Motor de combustión interna
              <br>
              Mantención del Vehículo
              <br>
              Responsabilidad y medio ambiente
              <br>
              Convivencia y Seguridad Vial
              <br>
              Propuesta valórica
              <br>
              La concentración en la conducción
              <br>
              Equilibrio emocional en la conducción
              <br>
              Conducción preventiva
              <br>
              Alcohol y drogas en la conducción
              <br>
              Evaluación Psicotécnica
              <br>
              Instrucción práctica en vehículo de doble comando
              <br>
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
              ¿Cuánto tiempo dura el curso de manejo?
            </button>
          </h2>
          <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse">
            <div class="accordion-body">
              El curso dura 18 dias entre clases prácticas y teóricas.
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFour" aria-expanded="false" aria-controls="panelsStayOpen-collapseFour">
              ¿Hay opciones de pago o financiamiento disponibles?
            </button>
          </h2>
          <div id="panelsStayOpen-collapseFour" class="accordion-collapse collapse">
            <div class="accordion-body">
              Si, existen diferentes formas de pago:
              <br>
              -Debito
              <br>
              -Credito
              <br>
              -Efectivo
              <br>
              -Transferencia
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFive" aria-expanded="false" aria-controls="panelsStayOpen-collapseFive">
              ¿Ofrecen clases teóricas y prácticas?
            </button>
          </h2>
          <div id="panelsStayOpen-collapseFive" class="accordion-collapse collapse">
            <div class="accordion-body">
              Sí. Nuestro programa contempla clases teoricas en sala y clases prácticas junto a nuestro profesores.
              
              
              
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseSix" aria-expanded="false" aria-controls="panelsStayOpen-collapseSix">
              ¿Tienen horarios flexibles para las clases?
            </button>
          </h2>
          <div id="panelsStayOpen-collapseSix" class="accordion-collapse collapse">
            <div class="accordion-body">
              Existen horarios flexibles en modalidad online sólo para clases teóricas.
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseSeven" aria-expanded="false" aria-controls="panelsStayOpen-collapseSeven">
              ¿Los instructores están certificados y tienen experiencia?
            </button>
          </h2>
          <div id="panelsStayOpen-collapseSeven" class="accordion-collapse collapse">
            <div class="accordion-body">
              Sí. Nuestros profesionales cuentan con varios años de experiencia y certificaciones
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseEight" aria-expanded="false" aria-controls="panelsStayOpen-collapseEight">
              ¿Proporcionan vehículos para las prácticas de manejo?
            </button>
          </h2>
          <div id="panelsStayOpen-collapseEight" class="accordion-collapse collapse">
            <div class="accordion-body">
              Si, tenemos una pequeña flota de vehiculos equipados 
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseNine" aria-expanded="false" aria-controls="panelsStayOpen-collapseNine">
              ¿Ofrecen clases para conductores principiantes y conductores experimentados?
            </button>
          </h2>
          <div id="panelsStayOpen-collapseNine" class="accordion-collapse collapse">
            <div class="accordion-body">
              Si, tenemos una variedad de cursos para distintos tipos de usuarios
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTen" aria-expanded="false" aria-controls="panelsStayOpen-collapseTen">
              ¿Cuál es el proceso para obtener la licencia de conducir después de completar el curso?
            </button>
          </h2>
          <div id="panelsStayOpen-collapseTen" class="accordion-collapse collapse">
            <div class="accordion-body">
              El siguiente paso es realizar el respectivo tramite en la municipalidad de residencia, donde puedes adjuntar el certificado de curso completado
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  
  

{% endblock %}

aplicacion/templates/Autoescuela/carrito.html
{% extends "Autoescuela/base.html" %}
{% load static %}

{% block title %}Carrito de Compras{% endblock %}

{% block contenido %}
<div class="container mt-5">
    <h2>Carrito de Compras</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Producto</th>
                <th>Precio</th>
                <th>Total</th>
                <th>Acción</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items_carrito %}
            <tr>
                <td>{{ item.producto.nombre }}</td>
                <td>{{ item.producto.precio }}</td>
                <td>{{ item.total_price }}</td>  
                <td>
                    <form method="post" action="{% url 'quitar_del_carrito' item.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Quitar</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h3>Total: {{ total }}</h3>
    <a href="{% url 'cursos' %}" class="btn btn-primary">Volver a Escoger Cursos</a>
    {% if tiene_items %}
    <a href="{% url 'formpago' %}" class="btn btn-success">Proceder a la Compra</a>
    {% endif %}
</div>
{% endblock %}

aplicacion/templates/Autoescuela/perfil.html
{% extends "Autoescuela/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Perfil{% endblock %}

{% block contenido %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6"> 
            <div class="card text-dark mb-3" style="max-width: 50rem;">
                <div class="card-header">INFORMACIÓN DE LA CUENTA</div>
                <div class="card-body"> 
                    <h6>Nombre: {{ usuario.nombre_estudiante }}</h6>
                    <hr>
                    <h6>Correo: {{ usuario.correo }}</h6>
                    <hr>
                    <h6>Dirección: 
                        {% if usuario.direccion %}
                            {{ usuario.direccion }}
                        {% else %}
                            No se ha ingresado
                        {% endif %}
                    </h6>
                    <hr>
                    <h6>Cursos Activos: 
                        <ul>
                        {% for compra in usuario.usuario.compra_set.all %}
                            {% for detalle in compra.detalles.all %}
                                <li>{{ detalle.producto.nombre }}</li>
                            {% endfor %}
                        {% endfor %}
                        </ul>
                    </h6>
                    <hr>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editarUs">
                        Editar
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-6"> 
            <div class="card text-dark mb-3" style="max-width: 16rem;"> 
                <img src="{% static 'aplicacion/img/avatar.webp' %}" alt="usuario" style="width: 15rem;">
            </div>
        </div>
    </div>
</div>

<div class="container-fluid contenedor-principal">
    <h2 class="mt-4 text-center">Horario Semanal</h2>
    <div class="row">
        <div class="col">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Hora</th>
                        <th>Lunes</th>
                        <th>Martes</th>
                        <th>Miércoles</th>
                        <th>Jueves</th>
                        <th>Viernes</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>10:00 - 11:30</td>
                        <td>-</td>
                        <td>Teórico</td>
                        <td>Teórico</td>
                        <td>-</td>
                        <td>Teórico</td>
                    </tr>
                    <tr>
                        <td>11:30 - 13:00</td>
                        <td>Práctico</td>
                        <td>Práctico</td>
                        <td>-</td>
                        <td>Práctico</td>
                        <td>Práctico</td>
                    </tr>
                    <tr>
                        <td>13:00 a 14:30</td>
                        <td>Teórico</td>
                        <td>Teórico</td>
                        <td>-</td>
                        <td>Teórico</td>
                        <td>Teórico</td>
                    </tr>
                    <tr>
                        <td>14:30 - 16:00</td>
                        <td>Práctico</td>
                        <td>Práctico</td>
                        <td>-</td>
                        <td>Práctico</td>
                        <td>-</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Modal para editar perfil -->
<div class="modal fade" id="editarUs" tabindex="-1" aria-labelledby="editUserForm" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editUserForm">Editar Datos</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- Formulario para editar perfil -->
                <form id="editUserForm" method="post" class="needs-validation" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <!-- Botón de guardar -->
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </form>
                <!-- Mensaje de guardado exitoso (oculto por defecto) -->
                <div class="alert alert-success mt-3 d-none" role="alert">
                    Guardado exitoso.
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal de eliminación -->
<div class="modal fade" id="eliminarUs" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Mensaje de Sistema</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ¡Eliminación de cuenta realizada!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}